---
- name: Ensure all configured dotfiles are links.
  shell: "ls -F {{ item.dest }}/{{ item.file }}"
  register: existing_dotfile_info
  failed_when: false
  check_mode: no
  changed_when: false
  with_items: "{{ dotfiles_files }}"

- name: Link dotfiles into home folder.
  file:
    src: "{{playbook_dir}}/{{ dotfiles_dir }}/{{ item.file }}"
    dest: "{{ item.dest }}/{{ item.file }}"
    state: link
  become: no
  with_items: "{{ dotfiles_files }}"